language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -q cmake
script: ./travis-ci.sh
branches:
  only:
    - master
    - develop
#matrix:
  #include:
    #- compiler: clang
      #env: OPTIONS="-DCOMPILER_IS_NOT_CXX11_READY=OFF"
notifications:
  irc:
    channels:
      - "chat.freenode.net#akagoria"
    on_success: change
    on_failure: always

